#!/bin/sh
# Build Busybox against Android's bionic
# Originally by Dan Fandrich
#
# Configure with "make android_defconfig"
#
# This file has been tested on Android Froyo (the lack of ttyname_r in
# the android libc must be patched around) and Gingerbread.

# Point this to the Android root directory; it's used in the defconfig CFLAGS
export A="/var/data/work/android-src"

# Toolchain version in use by this version of Android
GCCVER=4.4.3

export PATH="$A/prebuilt/linux-x86/toolchain/arm-eabi-$GCCVER/bin:$PATH"

# Set the linker flags; compiler flags are in the defconfig file
if grep "^CONFIG_STATIC=y" .config >/dev/null ; then
	# Static linking
	LDFLAGS="-static -Xlinker -z -Xlinker muldefs -nostdlib $A/prebuilt/ndk/android-ndk-r6/platforms/android-9/arch-arm/usr/lib/crtbegin_static.o $A/prebuilt/ndk/android-ndk-r6/platforms/android-9/arch-arm/usr/lib/crtend_android.o -L$A/prebuilt/ndk/android-ndk-r6/platforms/android-9/arch-arm/usr/lib"
	LDLIBS="m c gcc"
else
	# Dynamic linking
	LDFLAGS="-Xlinker -z -Xlinker muldefs -nostdlib -Bdynamic -Xlinker -T$A/build/core/armelf.x -Xlinker -dynamic-linker -Xlinker /system/bin/linker -Xlinker -z -Xlinker nocopyreloc -Xlinker --no-undefined $A/prebuilt/ndk/android-ndk-r6/platforms/android-9/arch-arm/usr/lib/crtbegin_static.o $A/prebuilt/ndk/android-ndk-r6/platforms/android-9/arch-arm/usr/lib/crtend_android.o -L$A/prebuilt/ndk/android-ndk-r6/platforms/android-9/arch-arm/usr/lib"
	LDLIBS="dl m c gcc"
fi

# It's possible with newer version
# you need to use CFLAGS_busybox instead of EXTRA_LDFLAGS below:
make EXTRA_LDFLAGS="$LDFLAGS" LDLIBS="$LDLIBS" "$@"
